// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: moderation_service.proto

package moderation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModerationService_ModerateContent_FullMethodName = "/moderation.ModerationService/ModerateContent"
	ModerationService_GetModelHealth_FullMethodName  = "/moderation.ModerationService/GetModelHealth"
)

// ModerationServiceClient is the client API for ModerationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModerationServiceClient interface {
	// ModerateContent performs bidirectional streaming moderation.
	// The client sends content identifiers and receives moderation results.
	ModerateContent(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ModerateContentRequest, ModerateContentResponse], error)
	// GetModelHealth returns the health status of the AI model.
	GetModelHealth(ctx context.Context, in *GetModelHealthRequest, opts ...grpc.CallOption) (*GetModelHealthResponse, error)
}

type moderationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModerationServiceClient(cc grpc.ClientConnInterface) ModerationServiceClient {
	return &moderationServiceClient{cc}
}

func (c *moderationServiceClient) ModerateContent(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ModerateContentRequest, ModerateContentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModerationService_ServiceDesc.Streams[0], ModerationService_ModerateContent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ModerateContentRequest, ModerateContentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModerationService_ModerateContentClient = grpc.BidiStreamingClient[ModerateContentRequest, ModerateContentResponse]

func (c *moderationServiceClient) GetModelHealth(ctx context.Context, in *GetModelHealthRequest, opts ...grpc.CallOption) (*GetModelHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelHealthResponse)
	err := c.cc.Invoke(ctx, ModerationService_GetModelHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModerationServiceServer is the server API for ModerationService service.
// All implementations must embed UnimplementedModerationServiceServer
// for forward compatibility.
type ModerationServiceServer interface {
	// ModerateContent performs bidirectional streaming moderation.
	// The client sends content identifiers and receives moderation results.
	ModerateContent(grpc.BidiStreamingServer[ModerateContentRequest, ModerateContentResponse]) error
	// GetModelHealth returns the health status of the AI model.
	GetModelHealth(context.Context, *GetModelHealthRequest) (*GetModelHealthResponse, error)
	mustEmbedUnimplementedModerationServiceServer()
}

// UnimplementedModerationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModerationServiceServer struct{}

func (UnimplementedModerationServiceServer) ModerateContent(grpc.BidiStreamingServer[ModerateContentRequest, ModerateContentResponse]) error {
	return status.Error(codes.Unimplemented, "method ModerateContent not implemented")
}
func (UnimplementedModerationServiceServer) GetModelHealth(context.Context, *GetModelHealthRequest) (*GetModelHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelHealth not implemented")
}
func (UnimplementedModerationServiceServer) mustEmbedUnimplementedModerationServiceServer() {}
func (UnimplementedModerationServiceServer) testEmbeddedByValue()                           {}

// UnsafeModerationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModerationServiceServer will
// result in compilation errors.
type UnsafeModerationServiceServer interface {
	mustEmbedUnimplementedModerationServiceServer()
}

func RegisterModerationServiceServer(s grpc.ServiceRegistrar, srv ModerationServiceServer) {
	// If the following call panics, it indicates UnimplementedModerationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModerationService_ServiceDesc, srv)
}

func _ModerationService_ModerateContent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ModerationServiceServer).ModerateContent(&grpc.GenericServerStream[ModerateContentRequest, ModerateContentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModerationService_ModerateContentServer = grpc.BidiStreamingServer[ModerateContentRequest, ModerateContentResponse]

func _ModerationService_GetModelHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).GetModelHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_GetModelHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).GetModelHealth(ctx, req.(*GetModelHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModerationService_ServiceDesc is the grpc.ServiceDesc for ModerationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModerationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moderation.ModerationService",
	HandlerType: (*ModerationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetModelHealth",
			Handler:    _ModerationService_GetModelHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ModerateContent",
			Handler:       _ModerationService_ModerateContent_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "moderation_service.proto",
}
