// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: moderation_service.proto

package moderation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModerateContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // "text" or "image"
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                                  // actual text or image URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModerateContentRequest) Reset() {
	*x = ModerateContentRequest{}
	mi := &file_moderation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerateContentRequest) ProtoMessage() {}

func (x *ModerateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerateContentRequest.ProtoReflect.Descriptor instead.
func (*ModerateContentRequest) Descriptor() ([]byte, []int) {
	return file_moderation_service_proto_rawDescGZIP(), []int{0}
}

func (x *ModerateContentRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ModerateContentRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ModerateContentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ModerateContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Result        *ModerationResult      `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModerateContentResponse) Reset() {
	*x = ModerateContentResponse{}
	mi := &file_moderation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerateContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerateContentResponse) ProtoMessage() {}

func (x *ModerateContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerateContentResponse.ProtoReflect.Descriptor instead.
func (*ModerateContentResponse) Descriptor() ([]byte, []int) {
	return file_moderation_service_proto_rawDescGZIP(), []int{1}
}

func (x *ModerateContentResponse) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ModerateContentResponse) GetResult() *ModerationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ModerationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContentId     string                 `protobuf:"bytes,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	IsApproved    bool                   `protobuf:"varint,3,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Categories    []string               `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	ModelName     string                 `protobuf:"bytes,6,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModerationResult) Reset() {
	*x = ModerationResult{}
	mi := &file_moderation_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerationResult) ProtoMessage() {}

func (x *ModerationResult) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerationResult.ProtoReflect.Descriptor instead.
func (*ModerationResult) Descriptor() ([]byte, []int) {
	return file_moderation_service_proto_rawDescGZIP(), []int{2}
}

func (x *ModerationResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModerationResult) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ModerationResult) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

func (x *ModerationResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ModerationResult) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ModerationResult) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModerationResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ModerationResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetModelHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelHealthRequest) Reset() {
	*x = GetModelHealthRequest{}
	mi := &file_moderation_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelHealthRequest) ProtoMessage() {}

func (x *GetModelHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelHealthRequest.ProtoReflect.Descriptor instead.
func (*GetModelHealthRequest) Descriptor() ([]byte, []int) {
	return file_moderation_service_proto_rawDescGZIP(), []int{3}
}

type GetModelHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelHealthResponse) Reset() {
	*x = GetModelHealthResponse{}
	mi := &file_moderation_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelHealthResponse) ProtoMessage() {}

func (x *GetModelHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelHealthResponse.ProtoReflect.Descriptor instead.
func (*GetModelHealthResponse) Descriptor() ([]byte, []int) {
	return file_moderation_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetModelHealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

var File_moderation_service_proto protoreflect.FileDescriptor

const file_moderation_service_proto_rawDesc = "" +
	"\n" +
	"\x18moderation_service.proto\x12\n" +
	"moderation\x1a\x1fgoogle/protobuf/timestamp.proto\"n\n" +
	"\x16ModerateContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"n\n" +
	"\x17ModerateContentResponse\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x124\n" +
	"\x06result\x18\x02 \x01(\v2\x1c.moderation.ModerationResultR\x06result\"\x93\x02\n" +
	"\x10ModerationResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\tR\tcontentId\x12\x1f\n" +
	"\vis_approved\x18\x03 \x01(\bR\n" +
	"isApproved\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x1e\n" +
	"\n" +
	"categories\x18\x05 \x03(\tR\n" +
	"categories\x12\x1d\n" +
	"\n" +
	"model_name\x18\x06 \x01(\tR\tmodelName\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x17\n" +
	"\x15GetModelHealthRequest\"2\n" +
	"\x16GetModelHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy2\xcc\x01\n" +
	"\x11ModerationService\x12^\n" +
	"\x0fModerateContent\x12\".moderation.ModerateContentRequest\x1a#.moderation.ModerateContentResponse(\x010\x01\x12W\n" +
	"\x0eGetModelHealth\x12!.moderation.GetModelHealthRequest\x1a\".moderation.GetModelHealthResponseBDZBgithub.com/mohammadpnp/content-moderator/api/moderation;moderationb\x06proto3"

var (
	file_moderation_service_proto_rawDescOnce sync.Once
	file_moderation_service_proto_rawDescData []byte
)

func file_moderation_service_proto_rawDescGZIP() []byte {
	file_moderation_service_proto_rawDescOnce.Do(func() {
		file_moderation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moderation_service_proto_rawDesc), len(file_moderation_service_proto_rawDesc)))
	})
	return file_moderation_service_proto_rawDescData
}

var file_moderation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_moderation_service_proto_goTypes = []any{
	(*ModerateContentRequest)(nil),  // 0: moderation.ModerateContentRequest
	(*ModerateContentResponse)(nil), // 1: moderation.ModerateContentResponse
	(*ModerationResult)(nil),        // 2: moderation.ModerationResult
	(*GetModelHealthRequest)(nil),   // 3: moderation.GetModelHealthRequest
	(*GetModelHealthResponse)(nil),  // 4: moderation.GetModelHealthResponse
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_moderation_service_proto_depIdxs = []int32{
	2, // 0: moderation.ModerateContentResponse.result:type_name -> moderation.ModerationResult
	5, // 1: moderation.ModerationResult.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: moderation.ModerationService.ModerateContent:input_type -> moderation.ModerateContentRequest
	3, // 3: moderation.ModerationService.GetModelHealth:input_type -> moderation.GetModelHealthRequest
	1, // 4: moderation.ModerationService.ModerateContent:output_type -> moderation.ModerateContentResponse
	4, // 5: moderation.ModerationService.GetModelHealth:output_type -> moderation.GetModelHealthResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_moderation_service_proto_init() }
func file_moderation_service_proto_init() {
	if File_moderation_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moderation_service_proto_rawDesc), len(file_moderation_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moderation_service_proto_goTypes,
		DependencyIndexes: file_moderation_service_proto_depIdxs,
		MessageInfos:      file_moderation_service_proto_msgTypes,
	}.Build()
	File_moderation_service_proto = out.File
	file_moderation_service_proto_goTypes = nil
	file_moderation_service_proto_depIdxs = nil
}
