// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: content_service.proto

package content

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentType int32

const (
	ContentType_CONTENT_TYPE_UNSPECIFIED ContentType = 0
	ContentType_CONTENT_TYPE_TEXT        ContentType = 1
	ContentType_CONTENT_TYPE_IMAGE       ContentType = 2
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "CONTENT_TYPE_UNSPECIFIED",
		1: "CONTENT_TYPE_TEXT",
		2: "CONTENT_TYPE_IMAGE",
	}
	ContentType_value = map[string]int32{
		"CONTENT_TYPE_UNSPECIFIED": 0,
		"CONTENT_TYPE_TEXT":        1,
		"CONTENT_TYPE_IMAGE":       2,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_content_service_proto_enumTypes[0].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_content_service_proto_enumTypes[0]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_content_service_proto_rawDescGZIP(), []int{0}
}

type ContentStatus int32

const (
	ContentStatus_CONTENT_STATUS_UNSPECIFIED ContentStatus = 0
	ContentStatus_CONTENT_STATUS_PENDING     ContentStatus = 1
	ContentStatus_CONTENT_STATUS_APPROVED    ContentStatus = 2
	ContentStatus_CONTENT_STATUS_REJECTED    ContentStatus = 3
)

// Enum value maps for ContentStatus.
var (
	ContentStatus_name = map[int32]string{
		0: "CONTENT_STATUS_UNSPECIFIED",
		1: "CONTENT_STATUS_PENDING",
		2: "CONTENT_STATUS_APPROVED",
		3: "CONTENT_STATUS_REJECTED",
	}
	ContentStatus_value = map[string]int32{
		"CONTENT_STATUS_UNSPECIFIED": 0,
		"CONTENT_STATUS_PENDING":     1,
		"CONTENT_STATUS_APPROVED":    2,
		"CONTENT_STATUS_REJECTED":    3,
	}
)

func (x ContentStatus) Enum() *ContentStatus {
	p := new(ContentStatus)
	*p = x
	return p
}

func (x ContentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_content_service_proto_enumTypes[1].Descriptor()
}

func (ContentStatus) Type() protoreflect.EnumType {
	return &file_content_service_proto_enumTypes[1]
}

func (x ContentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentStatus.Descriptor instead.
func (ContentStatus) EnumDescriptor() ([]byte, []int) {
	return file_content_service_proto_rawDescGZIP(), []int{1}
}

type Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          ContentType            `protobuf:"varint,3,opt,name=type,proto3,enum=content.ContentType" json:"type,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Status        ContentStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=content.ContentStatus" json:"status,omitempty"`
	ModerationId  *string                `protobuf:"bytes,6,opt,name=moderation_id,json=moderationId,proto3,oneof" json:"moderation_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_content_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_content_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_content_service_proto_rawDescGZIP(), []int{0}
}

func (x *Content) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Content) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Content) GetType() ContentType {
	if x != nil {
		return x.Type
	}
	return ContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *Content) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Content) GetStatus() ContentStatus {
	if x != nil {
		return x.Status
	}
	return ContentStatus_CONTENT_STATUS_UNSPECIFIED
}

func (x *Content) GetModerationId() string {
	if x != nil && x.ModerationId != nil {
		return *x.ModerationId
	}
	return ""
}

func (x *Content) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Content) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ModerationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContentId     string                 `protobuf:"bytes,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	IsApproved    bool                   `protobuf:"varint,3,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Categories    []string               `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"` // e.g., "hate", "spam"
	ModelName     string                 `protobuf:"bytes,6,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModerationResult) Reset() {
	*x = ModerationResult{}
	mi := &file_content_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerationResult) ProtoMessage() {}

func (x *ModerationResult) ProtoReflect() protoreflect.Message {
	mi := &file_content_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerationResult.ProtoReflect.Descriptor instead.
func (*ModerationResult) Descriptor() ([]byte, []int) {
	return file_content_service_proto_rawDescGZIP(), []int{1}
}

func (x *ModerationResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModerationResult) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ModerationResult) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

func (x *ModerationResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ModerationResult) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ModerationResult) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModerationResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ModerationResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          ContentType            `protobuf:"varint,2,opt,name=type,proto3,enum=content.ContentType" json:"type,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentRequest) Reset() {
	*x = CreateContentRequest{}
	mi := &file_content_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentRequest) ProtoMessage() {}

func (x *CreateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentRequest.ProtoReflect.Descriptor instead.
func (*CreateContentRequest) Descriptor() ([]byte, []int) {
	return file_content_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateContentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateContentRequest) GetType() ContentType {
	if x != nil {
		return x.Type
	}
	return ContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *CreateContentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CreateContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentResponse) Reset() {
	*x = CreateContentResponse{}
	mi := &file_content_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentResponse) ProtoMessage() {}

func (x *CreateContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentResponse.ProtoReflect.Descriptor instead.
func (*CreateContentResponse) Descriptor() ([]byte, []int) {
	return file_content_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateContentResponse) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRequest) Reset() {
	*x = GetContentRequest{}
	mi := &file_content_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRequest) ProtoMessage() {}

func (x *GetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRequest.ProtoReflect.Descriptor instead.
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return file_content_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetContentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentResponse) Reset() {
	*x = GetContentResponse{}
	mi := &file_content_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentResponse) ProtoMessage() {}

func (x *GetContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentResponse.ProtoReflect.Descriptor instead.
func (*GetContentResponse) Descriptor() ([]byte, []int) {
	return file_content_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetContentResponse) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type StreamModerationResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamModerationResultsRequest) Reset() {
	*x = StreamModerationResultsRequest{}
	mi := &file_content_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamModerationResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamModerationResultsRequest) ProtoMessage() {}

func (x *StreamModerationResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamModerationResultsRequest.ProtoReflect.Descriptor instead.
func (*StreamModerationResultsRequest) Descriptor() ([]byte, []int) {
	return file_content_service_proto_rawDescGZIP(), []int{6}
}

func (x *StreamModerationResultsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_content_service_proto protoreflect.FileDescriptor

const file_content_service_proto_rawDesc = "" +
	"\n" +
	"\x15content_service.proto\x12\acontent\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd2\x02\n" +
	"\aContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.content.ContentTypeR\x04type\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.content.ContentStatusR\x06status\x12(\n" +
	"\rmoderation_id\x18\x06 \x01(\tH\x00R\fmoderationId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x10\n" +
	"\x0e_moderation_id\"\x93\x02\n" +
	"\x10ModerationResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\tR\tcontentId\x12\x1f\n" +
	"\vis_approved\x18\x03 \x01(\bR\n" +
	"isApproved\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x1e\n" +
	"\n" +
	"categories\x18\x05 \x03(\tR\n" +
	"categories\x12\x1d\n" +
	"\n" +
	"model_name\x18\x06 \x01(\tR\tmodelName\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"m\n" +
	"\x14CreateContentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.content.ContentTypeR\x04type\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"C\n" +
	"\x15CreateContentResponse\x12*\n" +
	"\acontent\x18\x01 \x01(\v2\x10.content.ContentR\acontent\"#\n" +
	"\x11GetContentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x12GetContentResponse\x12*\n" +
	"\acontent\x18\x01 \x01(\v2\x10.content.ContentR\acontent\"9\n" +
	"\x1eStreamModerationResultsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId*Z\n" +
	"\vContentType\x12\x1c\n" +
	"\x18CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CONTENT_TYPE_TEXT\x10\x01\x12\x16\n" +
	"\x12CONTENT_TYPE_IMAGE\x10\x02*\x85\x01\n" +
	"\rContentStatus\x12\x1e\n" +
	"\x1aCONTENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CONTENT_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17CONTENT_STATUS_APPROVED\x10\x02\x12\x1b\n" +
	"\x17CONTENT_STATUS_REJECTED\x10\x032\x88\x02\n" +
	"\x0eContentService\x12N\n" +
	"\rCreateContent\x12\x1d.content.CreateContentRequest\x1a\x1e.content.CreateContentResponse\x12E\n" +
	"\n" +
	"GetContent\x12\x1a.content.GetContentRequest\x1a\x1b.content.GetContentResponse\x12_\n" +
	"\x17StreamModerationResults\x12'.content.StreamModerationResultsRequest\x1a\x19.content.ModerationResult0\x01B>Z<github.com/mohammadpnp/content-moderator/api/content;contentb\x06proto3"

var (
	file_content_service_proto_rawDescOnce sync.Once
	file_content_service_proto_rawDescData []byte
)

func file_content_service_proto_rawDescGZIP() []byte {
	file_content_service_proto_rawDescOnce.Do(func() {
		file_content_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_service_proto_rawDesc), len(file_content_service_proto_rawDesc)))
	})
	return file_content_service_proto_rawDescData
}

var file_content_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_content_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_content_service_proto_goTypes = []any{
	(ContentType)(0),                       // 0: content.ContentType
	(ContentStatus)(0),                     // 1: content.ContentStatus
	(*Content)(nil),                        // 2: content.Content
	(*ModerationResult)(nil),               // 3: content.ModerationResult
	(*CreateContentRequest)(nil),           // 4: content.CreateContentRequest
	(*CreateContentResponse)(nil),          // 5: content.CreateContentResponse
	(*GetContentRequest)(nil),              // 6: content.GetContentRequest
	(*GetContentResponse)(nil),             // 7: content.GetContentResponse
	(*StreamModerationResultsRequest)(nil), // 8: content.StreamModerationResultsRequest
	(*timestamppb.Timestamp)(nil),          // 9: google.protobuf.Timestamp
}
var file_content_service_proto_depIdxs = []int32{
	0,  // 0: content.Content.type:type_name -> content.ContentType
	1,  // 1: content.Content.status:type_name -> content.ContentStatus
	9,  // 2: content.Content.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: content.Content.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 4: content.ModerationResult.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: content.CreateContentRequest.type:type_name -> content.ContentType
	2,  // 6: content.CreateContentResponse.content:type_name -> content.Content
	2,  // 7: content.GetContentResponse.content:type_name -> content.Content
	4,  // 8: content.ContentService.CreateContent:input_type -> content.CreateContentRequest
	6,  // 9: content.ContentService.GetContent:input_type -> content.GetContentRequest
	8,  // 10: content.ContentService.StreamModerationResults:input_type -> content.StreamModerationResultsRequest
	5,  // 11: content.ContentService.CreateContent:output_type -> content.CreateContentResponse
	7,  // 12: content.ContentService.GetContent:output_type -> content.GetContentResponse
	3,  // 13: content.ContentService.StreamModerationResults:output_type -> content.ModerationResult
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_content_service_proto_init() }
func file_content_service_proto_init() {
	if File_content_service_proto != nil {
		return
	}
	file_content_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_service_proto_rawDesc), len(file_content_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_content_service_proto_goTypes,
		DependencyIndexes: file_content_service_proto_depIdxs,
		EnumInfos:         file_content_service_proto_enumTypes,
		MessageInfos:      file_content_service_proto_msgTypes,
	}.Build()
	File_content_service_proto = out.File
	file_content_service_proto_goTypes = nil
	file_content_service_proto_depIdxs = nil
}
